---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: accuknox-agents
  namespace: ${releaseNamespace}
spec:
  interval: 10m
  timeout: 1m
  url: "${helmMirrorURL:=oci://public.ecr.aws/k9v9d5v2/accuknox-agents}"
